name: bitacora_carabineros
description: Una aplicación para el registro de procedimientos de Carabineros.
publish_to: 'none' # Evita la publicación accidental en pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Dependencias de Firebase
  firebase_core: ^2.27.1
  cloud_firestore: ^4.15.9

  # Utilidades
  intl: ^0.19.0 # Para formateo de fechas

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
